const{ShifuEmbryo}=require("./core/engine");
const{Teacher}=require("./core/teacher");
const fs=require("fs");

const eng=ShifuEmbryo.deserialize(fs.readFileSync(".state/embryo_v2_taught.json","utf8"));
const teacher=new Teacher(eng);
const t0=Date.now();
console.log("Loaded: "+eng.stats().vocab+" words");

const lessons=[
{d:"neurology",t:"The patient presented with acute onset left hemiparesis and dysarthria. CT head was performed urgently to exclude intracranial hemorrhage. MRI brain showed acute ischemic infarct in the right middle cerebral artery territory. The neurologist recommended intravenous thrombolysis with alteplase. Patient was monitored in the stroke unit for neurological deterioration. Glasgow coma scale was assessed hourly and remained stable at 14. Dysphagia screening was performed prior to commencing oral intake. Physiotherapy and occupational therapy were consulted for rehabilitation."},
{d:"cardiology",t:"The patient was admitted with chest pain and elevated troponin levels. Electrocardiogram showed ST elevation in leads V1 through V4. The cardiologist performed emergency percutaneous coronary intervention. A drug eluting stent was placed in the left anterior descending artery. The patient was started on dual antiplatelet therapy with aspirin and ticagrelor. Echocardiogram revealed reduced left ventricular ejection fraction of 35 percent. Heart failure was managed with ramipril bisoprolol and spironolactone. Cardiac rehabilitation was arranged prior to discharge."},
{d:"respiratory",t:"The patient presented with worsening dyspnea and productive cough. Chest radiograph showed bilateral infiltrates consistent with pneumonia. Sputum cultures grew Streptococcus pneumoniae sensitive to amoxicillin. Oxygen saturation was maintained above 94 percent on nasal cannula. Arterial blood gas showed type 1 respiratory failure with hypoxemia. The patient was escalated to non invasive ventilation for respiratory support. Bronchoscopy was performed to obtain bronchoalveolar lavage samples. Pulmonary function tests showed obstructive pattern consistent with COPD."},
{d:"gastro",t:"The patient presented with hematemesis and melena requiring urgent endoscopy. Upper gastrointestinal endoscopy revealed a bleeding duodenal ulcer. Helicobacter pylori testing was positive and eradication therapy was commenced. Liver function tests showed elevated bilirubin and transaminases. Abdominal ultrasound demonstrated gallstones with dilated common bile duct. ERCP was performed to extract the common bile duct stone. The patient was started on proton pump inhibitor therapy with omeprazole. Colonoscopy showed multiple polyps which were removed by polypectomy."},
{d:"endocrine",t:"The patient was diagnosed with type 2 diabetes mellitus with HbA1c of 9.2 percent. Metformin was commenced as first line therapy alongside lifestyle modification. The patient developed diabetic ketoacidosis requiring insulin infusion. Thyroid function tests revealed elevated TSH with low free T4 consistent with hypothyroidism. Levothyroxine was prescribed with dose titration guided by TSH monitoring. Cortisol levels were measured to exclude adrenal insufficiency. Blood glucose monitoring showed improved glycemic control on treatment."},
{d:"pharmacology",t:"Aspirin inhibits cyclooxygenase and prevents platelet aggregation. Metformin reduces hepatic glucose production and improves insulin sensitivity. Levetiracetam is prescribed for seizure prophylaxis and epilepsy management. Amoxicillin is a penicillin antibiotic effective against gram positive organisms. Omeprazole is a proton pump inhibitor that reduces gastric acid secretion. Ramipril is an ACE inhibitor used for hypertension and heart failure. Bisoprolol is a beta blocker that reduces heart rate and blood pressure. Clopidogrel is an antiplatelet agent used alongside aspirin for stent patients."},
{d:"pharmacology2",t:"Warfarin is an anticoagulant that requires regular INR monitoring. Enoxaparin is a low molecular weight heparin used for thromboprophylaxis. Gabapentin is prescribed for neuropathic pain and seizure disorders. Dexamethasone is a corticosteroid used to reduce cerebral edema. Phenytoin is an antiepileptic drug with a narrow therapeutic index. Insulin glargine provides basal insulin coverage over 24 hours. Salbutamol is a bronchodilator used for acute asthma exacerbations. Furosemide is a loop diuretic used for fluid overload in heart failure."},
{d:"procedures",t:"Lumbar puncture is performed to obtain cerebrospinal fluid for analysis. Central venous catheter insertion requires sterile technique and ultrasound guidance. Chest drain insertion is indicated for pneumothorax and pleural effusion. Arterial blood gas sampling is performed from the radial artery. Nasogastric tube insertion is required for enteral feeding in dysphagia. Urinary catheterization is performed for acute urinary retention. Endotracheal intubation is performed for airway protection in obtunded patients. Cardioversion is performed for hemodynamically unstable atrial fibrillation."},
{d:"nursing",t:"Nursing assessment includes vital signs fluid balance and pain scoring. The nurse administered intravenous antibiotics as prescribed by the doctor. Patient was turned every two hours to prevent pressure ulcer formation. Early warning score was calculated and escalation protocol was followed. The nurse documented accurate intake and output measurements. Medication reconciliation was completed on admission by the pharmacist. Discharge planning commenced with the multidisciplinary team on day one. Patient education included medication compliance and follow up appointments."},
{d:"investigations",t:"Full blood count showed elevated white cell count consistent with infection. C reactive protein was markedly elevated at 250 milligrams per liter. Renal function tests showed acute kidney injury with elevated creatinine. Coagulation screen showed prolonged prothrombin time and elevated INR. Blood cultures were obtained prior to commencing empirical antibiotic therapy. Lactate was measured to assess tissue perfusion in suspected sepsis. Urine dipstick showed leukocytes and nitrites suggestive of urinary tract infection. Troponin levels were measured serially to diagnose acute myocardial infarction."},
{d:"direction",t:"Doctor treats patient. Patient receives treatment from doctor. Doctor prescribes medication. Medication is prescribed by doctor. Nurse administers drug. Drug is administered by nurse. Surgeon performs operation. Operation is performed by surgeon. Blood pressure rises. Antihypertensive lowers blood pressure. Infection causes fever. Antibiotics treat infection. Stroke causes weakness. Rehabilitation improves weakness. Diabetes causes hyperglycemia. Insulin lowers blood glucose."},
{d:"anatomy",t:"Heart pumps blood through arteries to organs and tissues. Lungs exchange oxygen and carbon dioxide in the alveoli. Kidneys filter blood and produce urine for excretion. Liver metabolizes drugs and produces bile for digestion. Brain controls movement and processes sensory information. Pancreas produces insulin to regulate blood glucose levels. The middle cerebral artery supplies the lateral surface of the cerebral hemisphere. The coronary arteries arise from the aortic root and supply the myocardium."},
{d:"differential",t:"Chest pain may indicate myocardial infarction or pulmonary embolism. Headache with neck stiffness suggests meningitis until proven otherwise. Acute abdominal pain requires exclusion of surgical causes. Shortness of breath may be cardiac or respiratory in origin. Confusion in elderly patients may indicate infection or metabolic disturbance. Weight loss with night sweats raises suspicion for malignancy or tuberculosis. Jaundice may be pre hepatic or post hepatic in origin."},
{d:"emergency",t:"Anaphylaxis requires immediate intramuscular adrenaline and intravenous fluids. Cardiac arrest management follows the advanced life support algorithm. Tension pneumothorax requires immediate needle decompression. Status epilepticus requires intravenous benzodiazepine followed by phenytoin. Acute upper gastrointestinal bleeding requires urgent endoscopy. Diabetic ketoacidosis requires intravenous insulin infusion and fluid resuscitation. Acute pulmonary edema is treated with oxygen furosemide and nitrates. Septic shock requires early antibiotics intravenous fluids and vasopressors."},
{d:"safety",t:"Medication errors are reduced by double checking high risk drugs. Allergies must be documented and verified before prescribing. Hand hygiene is the single most effective measure against hospital infection. Patient identification must be confirmed before any procedure or medication. Falls prevention requires assessment of mobility and environmental hazards. Venous thromboembolism prophylaxis should be prescribed for all inpatients. Antibiotic stewardship reduces resistance and improves clinical outcomes. Clinical handover must include diagnosis plan and outstanding investigations."},
{d:"pathology",t:"Atherosclerosis causes narrowing of arteries leading to ischemia. Thrombus formation in deep veins can embolize to the pulmonary arteries. Malignant cells invade surrounding tissue and metastasize to distant organs. Inflammatory mediators cause vasodilation increased permeability and pain. Fibrosis replaces normal tissue following chronic inflammation or injury. Autoimmune disease occurs when the immune system attacks self antigens. Necrosis results from irreversible cell injury due to ischemia or toxins."},
{d:"reasoning",t:"The history suggests an acute coronary syndrome based on chest pain and risk factors. Examination findings of bibasal crackles and elevated JVP indicate heart failure. Investigation results confirm the diagnosis of community acquired pneumonia. The management plan includes antibiotics fluid resuscitation and close monitoring. Prognosis depends on the severity of the underlying condition and comorbidities. Differential diagnosis should always consider life threatening conditions first. Response to treatment should be assessed within 48 to 72 hours."},
{d:"holistic",t:"The patient with diabetes was also treated for depression and anxiety. Chronic pain management requires both pharmacological and psychological approaches. Social isolation contributes to poor outcomes in elderly stroke patients. Nutritional assessment is essential for patients with chronic disease. Sleep disturbance affects recovery and should be addressed during admission. Palliative care focuses on symptom management and quality of life."},
{d:"rehab",t:"Early mobilization reduces hospital acquired complications. Physiotherapy improves motor function after stroke. Speech therapy is essential for patients with dysphagia and aphasia. Occupational therapy addresses activities of daily living and independence. Cognitive rehabilitation helps patients with traumatic brain injury. Goal setting should involve the patient and multidisciplinary team. Discharge planning begins on the day of admission."},
{d:"synthesis",t:"The elderly patient presented with confusion fever and elevated white cell count consistent with sepsis. Blood cultures were positive for Escherichia coli and intravenous antibiotics were commenced. Fluid resuscitation was initiated and vasopressors were required for hemodynamic support. The patient was transferred to the intensive care unit for close monitoring. Renal function deteriorated requiring renal replacement therapy. After seven days of treatment the patient improved and was stepped down to the medical ward. Multidisciplinary team review recommended rehabilitation prior to discharge."},
];

// Feed each lesson 3x through Teacher
console.log("\n=== 20 ROUNDS MEDICAL TEACHING (3x each) ===\n");
for(let i=0;i<lessons.length;i++){
  const l=lessons[i];
  for(let r=0;r<3;r++) teacher.lesson(l.t,l.d);
  const sents=l.t.split(/[.!?\n]+/).map(s=>s.trim()).filter(s=>s.length>10);
  const drill=sents.length?teacher.drill(sents[0]):null;
  console.log("R"+(i+1).toString().padStart(2)+" ["+l.d.padEnd(14)+"] drill="+(drill?.learned?"Y":"N")+" asym="+(drill?.asymmetry?.toFixed(3)||"n/a"));
}

// Spontaneous
console.log("\n=== SPONTANEOUS ===");
for(let i=0;i<5;i++){const sp=teacher.spontaneous();console.log("S"+(i+1)+" gen="+(sp.generated?.length||0)+" dec="+sp.decayed);}

// Results
const st=eng.stats();
console.log("\nFinal: v="+st.vocab+" t="+st.tokens+" s="+st.sentences);

console.log("\nDESCRIBE:");
[["doctor","patient"],["aspirin","stroke"],["insulin","diabetes"],["heart","failure"],["seizure","levetiracetam"],["infection","antibiotics"],["pain","analgesia"],["surgeon","operation"],["blood","pressure"],["chest","pain"]].forEach(([a,b])=>{const d=eng.describe(a,b);console.log("  "+a+"<->"+b+": \""+(d.description||"?")+"\" ("+(d.coherence||0).toFixed(3)+")");});

console.log("\nCOHERENCE:");
[["Doctor treats patient with medication.","Medication with patient treats doctor."],["Patient presents with acute onset left sided weakness.","Weakness sided left onset acute with presents patient."],["Aspirin inhibits cyclooxygenase and prevents platelet aggregation.","Aggregation platelet prevents and cyclooxygenase inhibits aspirin."],["The neurologist recommended thrombolysis with alteplase.","Alteplase with thrombolysis recommended neurologist the."]].forEach(([n,s])=>{const s1=eng.scoreSentence(n),s2=eng.scoreSentence(s);console.log("  "+s1.coherence.toFixed(3)+" vs "+s2.coherence.toFixed(3)+" ("+(s1.coherence>s2.coherence?"+":"")+(s1.coherence-s2.coherence).toFixed(3)+") "+n.slice(0,55));});

console.log("\nAFFINITY:");
[["doctor","patient"],["aspirin","stroke"],["insulin","diabetes"],["heart","failure"],["seizure","levetiracetam"],["infection","antibiotics"],["chest","pain"],["blood","pressure"],["kidney","creatinine"],["surgeon","operation"]].forEach(([a,b])=>{const af=eng.affinity(a,b);if(af.known)console.log("  "+a.padEnd(16)+"<->"+b.padEnd(16)+" mutual="+af.mutual.toFixed(3)+" orbit="+af.orbit.toFixed(3)+" pull="+af.pullAB.toFixed(3)+"/"+af.pullBA.toFixed(3));});

console.log("\nCORRECTION:");
["seisure","bi1ateral","hypertenslon","str0ke","levetlracetam","hemorrhaqe","dlagnosls","patiert","medlcation","clopldogrel"].forEach(g=>{const c=eng.correct(g);console.log("  "+g.padEnd(18)+" -> "+(c.candidates[0]?.word||"?"));});

console.log("\nTEACHER:");
const diag=teacher.diagnose();diag.needs.forEach(n=>console.log("  "+n.slice(0,100)));

fs.writeFileSync(".state/embryo_v2_tutored.json",eng.serialize());
console.log("\nSaved in "+((Date.now()-t0)/1000).toFixed(0)+"s");
