import { useState, useEffect, useRef, useCallback } from "react";
/* SHIFU v1.4.1 — A stone etched by exposure.
   The baby state is Form — structure before any data. feed() is the
   perturbation. 7 channels are faces of the same stone. Affinity
   predicts which unetched regions accept the chisel easiest.
   Engine source of truth: core/engine.js. */
const V=new Set("aeiou"),IDX={form:[0,16],ctx:[16,28],hist:[28,36],inf:[36,44],con:[44,52],exp:[52,60],all:[0,60]};
const OCR_T={"0,o":.1,"1,l":.2,"1,i":.2,"5,s":.3,"8,b":.3,"6,g":.4,"l,i":.2,"m,n":.4,"u,v":.5,"c,e":.5,"r,n":.3,"d,o":.3,"f,t":.4,"h,b":.4,"a,e":.4,"a,o":.4,"u,n":.4,"e,i":.4,"f,l":.4,"s,e":.5,"b,d":.4};
const RT={correction:{ocr:.7,form:.3,context:0,history:0,influence:0,contrast:0,expectation:0},meaning:{form:.20,context:.20,history:.10,influence:.15,contrast:.15,expectation:.20,ocr:0}};
const mn=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0,sd=a=>{const m=mn(a);return Math.sqrt(mn(a.map(v=>(v-m)**2)));};
function cos(a,b,lo,hi){let d=0,na=0,nb=0;for(let i=lo;i<hi;i++){d+=a[i]*b[i];na+=a[i]**2;nb+=b[i]**2;}na=Math.sqrt(na);nb=Math.sqrt(nb);return na<1e-6||nb<1e-6?0:d/(na*nb);}
function ocrD(a,b){a=a.toLowerCase();b=b.toLowerCase();if(a.length<b.length)return ocrD(b,a);if(!b.length)return a.length;let p=Array.from({length:b.length+1},(_,i)=>i);for(let i=0;i<a.length;i++){const c=[i+1];for(let j=0;j<b.length;j++){const k=[a[i],b[j]].sort().join(",");c.push(Math.min(p[j+1]+1,c[j]+1,p[j]+(a[i]===b[j]?0:(OCR_T[k]??1))));}p=c;}return p[b.length];}
// ═══ IndexedDB persistence (not localStorage) ═══
const IDB={open(){return new Promise((res,rej)=>{const r=indexedDB.open("shifu",1);r.onupgradeneeded=()=>r.result.createObjectStore("state");r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});},async get(key){const db=await this.open();return new Promise((res,rej)=>{const tx=db.transaction("state","readonly");const r=tx.objectStore("state").get(key);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error);});},async set(key,val){const db=await this.open();return new Promise((res,rej)=>{const tx=db.transaction("state","readwrite");tx.objectStore("state").put(val,key);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);});},async del(key){const db=await this.open();return new Promise((res,rej)=>{const tx=db.transaction("state","readwrite");tx.objectStore("state").delete(key);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);});}};
// ═══ Engine (source of truth: core/engine.js) ═══
class E{
constructor(){this.wf={};this.co={};this.wp={};this.bf={};this.fs={};this.ls={};this.eg={};this.ph={};this.nv={};this._pn={};this.sl={};this.sn={};this.sd={};this.nx={};this.px={};this.nx2={};this._gp=[];this._gsl=[];this._gfs=0;this._gwc=0;this.ns=0;this.nt=0;this._c={};this._il={};this._ib={};}
_ri(w){const l=w.length;(this._il[l]??=[]);if(!this._il[l].includes(w))this._il[l].push(w);for(let i=0;i<w.length-1;i++){const b=w.slice(i,i+2);(this._ib[b]??=[]);if(!this._ib[b].includes(w))this._ib[b].push(w);}}
_ca(g,r=2){g=g.toLowerCase();const c=new Set();for(let d=-r;d<=r;d++){const ws=this._il[g.length+d];if(ws)for(const w of ws)c.add(w);}for(let i=0;i<g.length-1;i++){const ws=this._ib[g.slice(i,i+2)];if(ws)for(const w of ws)c.add(w);}return[...c];}
feed(raw){const ws=(raw.toLowerCase().match(/[a-z0-9]+/g)||[]).filter(w=>w.length>1);if(ws.length<2)return 0;this.ns++;const sl=ws.length,unq=new Set(ws).size;this._gsl.push(sl);if(this._gsl.length>200)this._gsl=this._gsl.slice(-200);for(let i=0;i<ws.length;i++){const w=ws[i],rp=i/Math.max(ws.length-1,1);this.nt++;const isN=!(w in this.wf);this.wf[w]=(this.wf[w]||0)+1;this._gfs++;this._gwc=Object.keys(this.wf).length;if(isN)this._ri(w);(this.wp[w]??=[]).push(rp);if(this.wp[w].length>100)this.wp[w]=this.wp[w].slice(-100);this._gp.push(rp);if(this._gp.length>500)this._gp=this._gp.slice(-500);this.co[w]??={};const nb=new Set();for(let j=Math.max(0,i-3);j<Math.min(ws.length,i+4);j++){if(j!==i){this.co[w][ws[j]]=(this.co[w][ws[j]]||0)+1;nb.add(ws[j]);}}for(let k=0;k<w.length-1;k++)this.bf[w.slice(k,k+2)]=(this.bf[w.slice(k,k+2)]||0)+1;this.fs[w]??=this.ns;if(w in this.ls){(this.eg[w]??=[]).push(this.ns-this.ls[w]);if(this.eg[w].length>50)this.eg[w]=this.eg[w].slice(-50);}this.ls[w]=this.ns;(this.ph[w]??=[]).push(rp);if(this.ph[w].length>50)this.ph[w]=this.ph[w].slice(-50);if(this._pn[w]&&nb.size){const prev=this._pn[w],union=new Set([...prev,...nb]);(this.nv[w]??=[]).push(1-[...prev].filter(x=>nb.has(x)).length/Math.max(union.size,1));if(this.nv[w].length>50)this.nv[w]=this.nv[w].slice(-50);}this._pn[w]=nb;(this.sl[w]??=[]).push(sl);if(this.sl[w].length>50)this.sl[w]=this.sl[w].slice(-50);const mates=ws.filter(x=>x!==w);(this.sn[w]??=[]).push(mates.length?mates.filter(m=>(this.wf[m]||0)<3).length/mates.length:0);if(this.sn[w].length>50)this.sn[w]=this.sn[w].slice(-50);(this.sd[w]??=[]).push(unq/sl);if(this.sd[w].length>50)this.sd[w]=this.sd[w].slice(-50);if(i<ws.length-1){this.nx[w]??={};this.nx[w][ws[i+1]]=(this.nx[w][ws[i+1]]||0)+1;}if(i>0){this.px[w]??={};this.px[w][ws[i-1]]=(this.px[w][ws[i-1]]||0)+1;}if(i<ws.length-2){const b=ws[i+1],c2=ws[i+2];this.nx2[w]??={};this.nx2[w][b]??={};this.nx2[w][b][c2]=(this.nx2[w][b][c2]||0)+1;}}this._c={};return ws.length;}
feedText(t){const s=t.split(/[.!?\n]+/).map(s=>s.trim()).filter(s=>s.length>5);let n=0;s.forEach(x=>n+=this.feed(x));return{sentences:s.length,tokens:n};}
fv(w){w=w.toLowerCase();const n=w.length;if(n<1)return new Float64Array(16);const f=new Float64Array(16),ch=Array.from(w).map(c=>V.has(c)?1:-1);if(n>=2)f[0]=ch.reduce((a,c,i)=>i>0&&c!==ch[i-1]?a+1:a,0)/(n-1);let mx=0,r=0;for(const c of ch){if(c<0){r++;mx=Math.max(mx,r);}else r=0;}f[1]=mx/n;mx=0;r=0;for(const c of ch){if(c>0){r++;mx=Math.max(mx,r);}else r=0;}f[2]=mx/n;f[3]=ch[0];f[4]=ch[n-1];if(n>=3){const t=Math.floor(n/3);f[5]=mn(ch.slice(2*t))-mn(ch.slice(0,t));}f[6]=ch.filter(c=>c>0).length/n;if(n>=2){const mu=mn(ch);f[7]=Math.sqrt(mn(ch.map(c=>(c-mu)**2)));}if(n>=2){let cv=0,vc=0,cc=0,vv=0;for(let i=0;i<n-1;i++){const a=V.has(w[i]),b=V.has(w[i+1]);if(!a&&b)cv++;else if(a&&!b)vc++;else if(!a&&!b)cc++;else vv++;}const t=n-1;f[8]=cv/t;f[9]=vc/t;f[10]=cc/t;f[11]=vv/t;}if(n>=3){let cvc=0,vcv=0;const iv=Array.from(w).map(c=>V.has(c));for(let i=0;i<n-2;i++){if(!iv[i]&&iv[i+1]&&!iv[i+2])cvc++;if(iv[i]&&!iv[i+1]&&iv[i+2])vcv++;}f[12]=cvc/(n-2);f[13]=vcv/(n-2);}f[14]=new Set(w).size/n;f[15]=Math.min(n/15,1);return f;}
cv(w){w=w.toLowerCase();const s=new Float64Array(12),co=this.co[w];if(!co)return s;const ent=Object.entries(co).sort((a,b)=>b[1]-a[1]),tot=ent.reduce((a,[,c])=>a+c,0),nN=ent.length;s[0]=Math.min(nN/30,1);s[1]=ent[0]?ent[0][1]/tot:0;s[2]=ent.slice(0,3).reduce((a,[,c])=>a+c,0)/(tot||1);const tf=ent.slice(0,5).map(([nb])=>Math.log2((this.wf[nb]||0)+1));if(tf.length){s[3]=mn(tf)/10;s[4]=tf.length>1?sd(tf)/5:0;}const np=[];for(const[nb]of ent.slice(0,10)){const p=this.wp[nb];if(p)np.push(...p.slice(-10));}if(np.length){s[5]=mn(np);s[6]=np.length>1?sd(np):0;}const mp=this.wp[w];if(mp?.length){s[7]=mn(mp);s[8]=mp.length>1?sd(mp):0;}if(nN>=2){const tn=ent[0][0],tc=this.co[tn]||{};const mk=new Set(Object.keys(co)),tk=new Set(Object.keys(tc)),un=new Set([...mk,...tk]);s[9]=1-[...mk].filter(x=>tk.has(x)).length/Math.max(un.size,1);}s[10]=Math.min(Math.log2((this.wf[w]||0)+1)/10,1);s[11]=tot/Math.max(this.wf[w]||1,1)/10;return s;}
hv(w){w=w.toLowerCase();const s=new Float64Array(8),cnt=this.wf[w]||0;if(!cnt)return s;s[0]=Math.min(Math.log2(cnt+1)/10,1);s[1]=Math.min((this.ns-(this.fs[w]||this.ns)+1)/(this.ns||1),1);s[2]=Math.max(0,1-(this.ns-(this.ls[w]||0))/(this.ns||1));const g=this.eg[w]||[];if(g.length>=2)s[3]=1-Math.min(sd(g)/(mn(g)+1e-3),2)/2;else if(g.length===1)s[3]=.5;const ph=this.ph[w]||[];if(ph.length>=2)s[4]=1-Math.min(sd(ph)*3,1);if(ph.length)s[5]=mn(ph);const v=this.nv[w]||[];if(v.length)s[6]=mn(v);s[7]=Math.min(cnt/10,1);return s;}
iv(w){w=w.toLowerCase();const s=new Float64Array(8),co=this.co[w];if(!co)return s;const sl=this.sl[w]||[];if(sl.length)s[0]=Math.min(mn(sl)/15,1);if(sl.length>=2)s[1]=Math.min(sd(sl)/5,1);const sn2=this.sn[w]||[];if(sn2.length)s[2]=mn(sn2);const dv=this.sd[w]||[];if(dv.length)s[3]=mn(dv);const nbs=Object.keys(co);if(nbs.length>=3){let tri=0,pr=0;const sa=nbs.slice(0,10);for(let i=0;i<sa.length;i++)for(let j=i+1;j<sa.length;j++){pr++;if(this.co[sa[i]]&&sa[j] in this.co[sa[i]])tri++;}s[4]=pr?1-tri/pr:0;}const pos=this.wp[w]||[];if(pos.length)s[5]=Math.abs(mn(pos)-0.5)*2;if(nbs.length){const nf=nbs.slice(0,10).map(n=>Math.log2((this.wf[n]||0)+1));s[6]=Math.min(sd(nf)/3,1);}if(sl.length>=4){const h=Math.floor(sl.length/2);const e2=mn(sl.slice(0,h)),l=mn(sl.slice(h));s[7]=e2>0?1-Math.min(Math.abs(l-e2)/e2,1):0;}return s;}
cnv(w){w=w.toLowerCase();const s=new Float64Array(8),cnt=this.wf[w]||0;if(!cnt||!this._gwc)return s;const avg=this._gfs/Math.max(this._gwc,1);s[0]=avg>0?Math.min(Math.abs(cnt-avg)/avg,2)/2:0;const wp=this.wp[w]||[],gp=this._gp;if(wp.length&&gp.length)s[1]=Math.min(Math.abs(mn(wp)-mn(gp))*3,1);if(wp.length>=2&&gp.length>=2)s[2]=Math.min(Math.abs(sd(wp)-sd(gp))*5,1);const sl=this.sl[w]||[],gsl=this._gsl;if(sl.length&&gsl.length)s[3]=Math.min(Math.abs(mn(sl)-mn(gsl))/Math.max(mn(gsl),1),1);const nbs=Object.keys(this.co[w]||{}).length;const avgN=Object.values(this.co).reduce((a,c)=>a+Object.keys(c).length,0)/Math.max(this._gwc,1);s[4]=avgN>0?Math.min(Math.abs(nbs-avgN)/avgN,2)/2:0;const co=this.co[w];if(co){const my=new Set(Object.keys(co));const tw=Object.entries(this.wf).sort((a,b)=>b[1]-a[1])[0];if(tw){const tn=new Set(Object.keys(this.co[tw[0]]||{}));const un=new Set([...my,...tn]);s[5]=un.size?1-[...my].filter(x=>tn.has(x)).length/un.size:0;}}const mxF=Math.max(...Object.values(this.wf),1);s[6]=1-Math.min(cnt/mxF,1);if(wp.length>=6){const h=Math.floor(wp.length/2);const eS=sd(wp.slice(0,h)),lS=sd(wp.slice(h));s[7]=eS>0?Math.max(0,1-lS/eS):0;}return s;}
ev(w){w=w.toLowerCase();const s=new Float64Array(8);const nx=this.nx[w],px=this.px[w];if(!nx&&!px)return s;if(nx){const ent=Object.entries(nx),tot=ent.reduce((a,[,c])=>a+c,0);const top=ent.sort((a,b)=>b[1]-a[1])[0];s[0]=top?top[1]/tot:0;}if(nx)s[1]=Math.min(Object.keys(nx).length/15,1);if(px){const ent=Object.entries(px),tot=ent.reduce((a,[,c])=>a+c,0);const top=ent.sort((a,b)=>b[1]-a[1])[0];s[2]=top?top[1]/tot:0;}if(px)s[3]=Math.min(Object.keys(px).length/15,1);s[4]=Math.abs((s[0]||0)-(s[2]||0));const fN=nx?Object.keys(nx).length:0,bN=px?Object.keys(px).length:0;s[5]=Math.min((fN+bN)/20,1);if(nx&&px){const fw=new Set(Object.keys(nx)),bw=new Set(Object.keys(px));const un=new Set([...fw,...bw]);s[6]=un.size?1-[...fw].filter(x=>bw.has(x)).length/un.size:0;}if(nx){const ent=Object.entries(nx).sort((a,b)=>b[1]-a[1]);const tot=ent.reduce((a,[,c])=>a+c,0);s[7]=tot?ent.slice(0,3).reduce((a,[,c])=>a+c,0)/tot:0;}return s;}
vec(w){const k=w.toLowerCase().trim();if(this._c[k])return this._c[k];const v=[...this.fv(k),...this.cv(k),...this.hv(k),...this.iv(k),...this.cnv(k),...this.ev(k)];this._c[k]=v;return v;}
cmp(a,b,p="meaning"){const va=this.vec(a),vb=this.vec(b);const sc={form:cos(va,vb,...IDX.form),context:cos(va,vb,...IDX.ctx),history:cos(va,vb,...IDX.hist),influence:cos(va,vb,...IDX.inf),contrast:cos(va,vb,...IDX.con),expectation:cos(va,vb,...IDX.exp),ocr:Math.max(0,1-ocrD(a,b)/Math.max(a.length,b.length,1))};sc.full=cos(va,vb,...IDX.all);const al=a.toLowerCase(),bl=b.toLowerCase();const nxA=this.nx[al],nxB=this.nx[bl];sc.expectsAB=nxA?((nxA[bl]||0)/Math.max(Object.values(nxA).reduce((x,y)=>x+y,0),1)):0;sc.expectsBA=nxB?((nxB[al]||0)/Math.max(Object.values(nxB).reduce((x,y)=>x+y,0),1)):0;sc.directional=Math.abs(sc.expectsAB-sc.expectsBA);const nx2AB=this.nx2[al]?.[bl],nx2BA=this.nx2[bl]?.[al];sc.trajectoryAB=nx2AB?Math.min(Object.keys(nx2AB).length/5,1):0;sc.trajectoryBA=nx2BA?Math.min(Object.keys(nx2BA).length/5,1):0;const rt=RT[p];return{routed:Object.entries(rt).reduce((s,[ch,w])=>s+w*(sc[ch]||0),0),...sc,wt:rt};}
correct(g,k=5){const out=this._ca(g).map(w=>({word:w,...this.cmp(g,w,"correction")}));out.sort((a,b)=>b.routed-a.routed||(this.wf[b.word]||0)-(this.wf[a.word]||0));const top=out.slice(0,k);return{candidates:top,conf:top.length>=2?top[0].routed-top[1].routed:top.length?1:0};}
similar(w,k=8){const key=w.toLowerCase(),out=[];for(const c of Object.keys(this.wf)){if(c===key)continue;out.push({word:c,...this.cmp(w,c,"meaning")});}return out.sort((a,b)=>b.routed-a.routed).slice(0,k);}
affinity(a,b){a=a.toLowerCase();b=b.toLowerCase();const r={a,b};r.formRes=cos(this.fv(a),this.fv(b),0,16);const coA=this.co[a],coB=this.co[b];if(coA&&coB){const nbA=Object.keys(coA),nbBs=new Set(Object.keys(coB));const shared=nbA.filter(x=>nbBs.has(x));if(shared.length){const wt=w=>1/Math.max(Math.log2((this.wf[w]||0)+1),1);const sw=shared.reduce((s,w)=>s+wt(w),0);const tw=nbA.reduce((s,w)=>s+wt(w),0)+[...nbBs].reduce((s,w)=>s+wt(w),0)-sw;r.orbit=tw>0?sw/tw:0;}else r.orbit=0;}else r.orbit=0;const nxA=this.nx[a],nxB=this.nx[b];const tA=nxA?Object.values(nxA).reduce((s,v)=>s+v,0):0,tB=nxB?Object.values(nxB).reduce((s,v)=>s+v,0):0;r.pullAB=tA?(nxA[b]||0)/tA:0;r.pullBA=tB?(nxB[a]||0)/tB:0;let iAB=0,iBA=0;if(nxA)for(const mid of Object.keys(nxA))if(this.nx[mid]?.[b])iAB++;if(nxB)for(const mid of Object.keys(nxB))if(this.nx[mid]?.[a])iBA++;r.indAB=Math.min(iAB/5,1);r.indBA=Math.min(iBA/5,1);r.conAlign=cos(this.cnv(a),this.cnv(b),0,8);r.expOvlp=cos(this.ev(a),this.ev(b),0,8);r.afAB=r.formRes*.05+r.orbit*.35+r.pullAB*.20+r.indAB*.20+r.conAlign*.05+r.expOvlp*.15;r.afBA=r.formRes*.05+r.orbit*.35+r.pullBA*.20+r.indBA*.20+r.conAlign*.05+r.expOvlp*.15;r.mutual=(r.afAB+r.afBA)/2;r.asym=Math.abs(r.afAB-r.afBA);return r;}
// scoreSentence with affinity gating: high-affinity arrivals cost less surprise
scoreSentence(raw){const ws=(raw.toLowerCase().match(/[a-z0-9]+/g)||[]).filter(w=>w.length>1);if(ws.length<2)return{words:ws,steps:[],meanSurprise:0,coherence:0};const steps=[];let tot=0;const cf=new Map();for(let i=0;i<ws.length;i++){const w=ws[i];const st={word:w,pos:i};if(i>0){const nxP=this.nx[ws[i-1]],t=nxP?Object.values(nxP).reduce((a,b)=>a+b,0):0;st.seqS=1-(nxP?((nxP[w]||0)/Math.max(t,1)):0);}else st.seqS=0;if(i>=2){const nx2pp=this.nx2[ws[i-2]]?.[ws[i-1]],t=nx2pp?Object.values(nx2pp).reduce((a,b)=>a+b,0):0;st.trajS=1-(nx2pp?((nx2pp[w]||0)/Math.max(t,1)):0);}else st.trajS=0;if(i>0&&cf.size>0){const fw=cf.get(w)||0;st.fieldS=1-fw/Math.max(...cf.values(),1);}else st.fieldS=0;
// Affinity gate: quick shared-orbit Jaccard with previous word
if(i>0){const pCo=this.co[ws[i-1]],wCo=this.co[w];if(pCo&&wCo){const pN=Object.keys(pCo),wN=new Set(Object.keys(wCo));const sh=pN.filter(x=>wN.has(x)).length;const un=new Set([...pN,...wN]).size;st.afGate=un?sh/un:0;}else st.afGate=0;}else st.afGate=0;
const base=.35*st.seqS+.30*(i>=2?st.trajS:st.seqS)+.35*(i>0?st.fieldS:0);
st.surprise=base*(1-st.afGate*0.3); // affinity reduces surprise up to 30%
tot+=st.surprise;st.cumS=tot;steps.push(st);const co=this.co[w];if(co)for(const[nb,cnt]of Object.entries(co))cf.set(nb,(cf.get(nb)||0)+cnt);cf.set(w,(cf.get(w)||0)+10);}const ms=steps.length?tot/steps.length:0;return{words:ws,steps,meanSurprise:ms,coherence:1-Math.min(ms,1)};}
stats(){return{vocab:Object.keys(this.wf).length,sent:this.ns,tokens:this.nt};}
save(){const tr=(o,n)=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,Array.isArray(v)?v.slice(-n):v]));return JSON.stringify({wf:this.wf,co:this.co,wp:tr(this.wp,50),bf:this.bf,fs:this.fs,ls:this.ls,eg:tr(this.eg,30),ph:tr(this.ph,30),nv:tr(this.nv,20),sl:tr(this.sl,30),sn:tr(this.sn,30),sd:tr(this.sd,30),nx:this.nx,px:this.px,nx2:this.nx2,gp:this._gp.slice(-200),gsl:this._gsl.slice(-200),gfs:this._gfs,gwc:this._gwc,pn:Object.fromEntries(Object.entries(this._pn).map(([k,v])=>[k,[...v]])),ns:this.ns,nt:this.nt});}
static from(j){const d=JSON.parse(j),e=new E();e.wf=d.wf||{};e.co=d.co||{};e.wp=d.wp||{};e.bf=d.bf||{};e.fs=d.fs||{};e.ls=d.ls||{};e.eg=d.eg||{};e.ph=d.ph||{};e.nv=d.nv||{};e.sl=d.sl||{};e.sn=d.sn||{};e.sd=d.sd||{};e.nx=d.nx||{};e.px=d.px||{};e.nx2=d.nx2||{};e._gp=d.gp||[];e._gsl=d.gsl||[];e._gfs=d.gfs||0;e._gwc=d.gwc||0;if(d.pn)e._pn=Object.fromEntries(Object.entries(d.pn).map(([k,v])=>[k,new Set(v)]));e.ns=d.ns||0;e.nt=d.nt||0;for(const w of Object.keys(e.wf))e._ri(w);return e;}}
// ═══ Intent + Response ═══
function parseIntent(input){const t=input.trim(),tl=t.toLowerCase();
if(/^(feed|learn|read|absorb)[\s:]/i.test(tl))return{type:"feed",text:t.replace(/^(feed|learn|read|absorb)[\s:]*/i,"").trim()};
if(/^(correct|fix|ocr)[\s:]/i.test(tl))return{type:"correct",text:t.replace(/^(correct|fix|ocr)[\s:]*/i,"").trim()};
if(/^(score|coherence|walk)[\s:]/i.test(tl))return{type:"score",text:t.replace(/^(score|coherence|walk)[\s:]*/i,"").trim()};
if(/^(compare|vs)[\s:]/i.test(tl)){const p=t.replace(/^(compare|vs)[\s:]*/i,"").split(/\s+(and|vs|with|to)\s+/i);if(p.length>=2)return{type:"compare",a:p[0].trim(),b:p[p.length-1].trim()};}
if(/^(affinity|attract|bond)[\s:]/i.test(tl)){const p=t.replace(/^(affinity|attract|bond)[\s:]*/i,"").split(/\s+(and|vs|with|to)\s+/i);if(p.length>=2)return{type:"affinity",a:p[0].trim(),b:p[p.length-1].trim()};}
if(/^(what is|explore|lookup|define|about)[\s:]/i.test(tl))return{type:"explore",word:t.replace(/^(what is|explore|lookup|define|about)[\s:]*/i,"").trim().split(/\s/)[0]};
if(/^(stats|status|vocabulary)$/i.test(tl))return{type:"stats"};
if(/^(reset|clear|forget)$/i.test(tl))return{type:"reset"};
if(/^(help|\?)$/i.test(tl))return{type:"help"};
const words=tl.split(/\s+/);if(words.length===1&&words[0].length>2)return{type:"explore",word:words[0]};
return{type:"feed",text:t};}
function respond(intent,eng){const s=eng.stats();switch(intent.type){
case"feed":{if(!intent.text)return{text:"Give me text to learn.",rich:null};const b=s.vocab;const r=eng.feedText(intent.text);const a=Object.keys(eng.wf).length;return{text:`Fed ${r.sentences} sentence${r.sentences!==1?"s":""}, ${r.tokens} tokens. +${a-b} new words. Vocabulary: ${a}.`,rich:null};}
case"explore":{const w=intent.word.toLowerCase();if(!eng.wf[w])return{text:`I don't know "${w}" yet. Feed me text containing it.`,rich:null};const freq=eng.wf[w];const sim=eng.similar(w,5);const nx=eng.nx[w]?Object.entries(eng.nx[w]).sort((a,b)=>b[1]-a[1]).slice(0,5):[];const vec=eng.vec(w);const chs=["form","context","history","influence","contrast","expectation"];const energy=chs.map((ch,ci)=>{const lo=IDX[["form","ctx","hist","inf","con","exp"][ci]][0],hi=IDX[["form","ctx","hist","inf","con","exp"][ci]][1];return[ch,vec.slice(lo,hi).reduce((a,v)=>a+v*v,0)];}).sort((a,b)=>b[1]-a[1]);let txt=`"${w}" — seen ${freq}x.\nStrongest: ${energy[0][0]} (${energy[0][1].toFixed(2)}).`;if(sim.length)txt+=`\nSimilar: ${sim.map(s=>`${s.word} ${(s.routed*100).toFixed(0)}%`).join(", ")}.`;if(nx.length)txt+=`\nExpects next: ${nx.map(([w,c])=>`${w} (${c}x)`).join(", ")}.`;return{text:txt,rich:{type:"channels",energy}};}
case"compare":{const{a,b}=intent;if(!a||!b)return{text:"Compare what? Try: compare doctor and aspirin",rich:null};const r=eng.cmp(a,b,"meaning");let txt=`${a} ↔ ${b}: ${(r.routed*100).toFixed(1)}%\n`;const chs=["form","context","history","influence","contrast","expectation"];txt+=chs.map(ch=>`${ch} ${(r[ch]*100).toFixed(0)}%`).join(" · ");if(r.directional>0.001)txt+=`\n${a}→${b}: ${(r.expectsAB*100).toFixed(1)}%  ${b}→${a}: ${(r.expectsBA*100).toFixed(1)}%`;if(r.trajectoryAB>0||r.trajectoryBA>0)txt+=`\nTrajectory ${a}→${b}→?: ${(r.trajectoryAB*100).toFixed(0)}%  ${b}→${a}→?: ${(r.trajectoryBA*100).toFixed(0)}%`;return{text:txt,rich:{type:"direction",a,b,...r}};}
case"affinity":{const{a,b}=intent;if(!a||!b)return{text:"Affinity between what? Try: affinity doctor and garlic",rich:null};if(!eng.wf[a.toLowerCase()]||!eng.wf[b.toLowerCase()])return{text:`I need to know both words first. Feed me text containing "${!eng.wf[a.toLowerCase()]?a:b}".`,rich:null};const r=eng.affinity(a,b);let txt=`Affinity: ${a} ↔ ${b}\n`;txt+=`${a}→${b}: ${(r.afAB*100).toFixed(1)}%  ${b}→${a}: ${(r.afBA*100).toFixed(1)}%  mutual: ${(r.mutual*100).toFixed(1)}%\n\n`;txt+=`Shared orbit: ${(r.orbit*100).toFixed(0)}%${r.orbit>.1?" — shared neighbors":""}`;txt+=`\nDirect pull: ${a}→${b} ${(r.pullAB*100).toFixed(0)}%  ${b}→${a} ${(r.pullBA*100).toFixed(0)}%`;txt+=`\nIndirect: ${a}→?→${b} ${(r.indAB*100).toFixed(0)}%  ${b}→?→${a} ${(r.indBA*100).toFixed(0)}%`;if(r.asym>.01)txt+=`\n${r.afAB>r.afBA?a+" pulls "+b:b+" pulls "+a} more (${(r.asym*100).toFixed(1)}% asymmetry)`;return{text:txt,rich:{type:"affinity",...r}};}
case"correct":{const words=intent.text.split(/\s+/);const results=words.map(w=>{if(eng.wf[w.toLowerCase()])return{orig:w,known:true,top:w};const r=eng.correct(w,3);return{orig:w,known:false,top:r.candidates[0]?.word,conf:r.conf};});return{text:results.map(r=>r.known?`${r.orig} ✓`:r.top?`${r.orig} → ${r.top} (Δ${r.conf.toFixed(3)})`:`${r.orig} → ?`).join("\n")+"\n\nVerify all corrections.",rich:null};}
case"score":{const r=eng.scoreSentence(intent.text);return{text:`Coherence: ${(r.coherence*100).toFixed(1)}%  Surprise: ${r.meanSurprise.toFixed(3)}`,rich:{type:"score",...r}};}
case"stats":return{text:`${s.vocab} words · ${s.sent} sentences · ${s.tokens} tokens\n60D · 7 channels · affinity-gated scoring`,rich:null};
case"reset":return{text:"__RESET__",rich:null};
case"help":return{text:`Talk naturally, or use commands:\n\nfeed: [text] — teach me\nexplore [word] — what do I know?\ncompare [a] and [b] — similarity + direction\naffinity [a] and [b] — pre-contact attraction\ncorrect [text] — fix garbled words\nscore: [sentence] — coherence walk\nstats — what have I learned?\nreset — forget everything\n\nOr just type text — I'll learn it.`,rich:null};
default:return{text:"Type help to see what I can do.",rich:null};}}
// ═══ Rich Viz ═══
const CC={"form":"#48b89a","context":"#c4943a","history":"#8a6abf","influence":"#e06050","contrast":"#5a8ac9","expectation":"#d4a843"};
function RichViz({data}){if(!data)return null;
if(data.type==="channels")return<div style={{display:"flex",gap:4,flexWrap:"wrap",marginTop:6}}>{data.energy.map(([ch,e])=><div key={ch} style={{display:"flex",alignItems:"center",gap:4,padding:"2px 8px",background:"#0a0e14",borderRadius:4,border:"1px solid #1a2130"}}><span style={{fontSize:8,color:CC[ch],fontWeight:700}}>{ch}</span><div style={{width:40,height:3,background:"#0a0e14",borderRadius:2}}><div style={{width:`${Math.min(e/2,1)*100}%`,height:"100%",background:CC[ch],borderRadius:2}}/></div><span style={{fontSize:7,color:"#4a5a6a"}}>{e.toFixed(2)}</span></div>)}</div>;
if(data.type==="direction"&&data.directional>0.001)return<div style={{marginTop:6,padding:6,background:"#0a0e14",borderRadius:6,border:"1px solid #1a2130",fontSize:9}}><span style={{color:"#48b89a"}}>{data.a}→{data.b}</span> <b>{(data.expectsAB*100).toFixed(1)}%</b><span style={{color:"#4a5a6a",margin:"0 8px"}}>|</span><span style={{color:"#4a5a6a"}}>{data.b}→{data.a}</span> <b>{(data.expectsBA*100).toFixed(1)}%</b></div>;
if(data.type==="affinity")return<div style={{marginTop:6,padding:8,background:"#0a0e14",borderRadius:6,border:"1px solid #1a2130"}}><div style={{display:"flex",gap:6,flexWrap:"wrap",fontSize:8}}>{[["orbit",data.orbit,"#48b89a"],["pull→",data.pullAB,"#d4a843"],["←pull",data.pullBA,"#c4943a"],["ind→",data.indAB,"#8a6abf"],["←ind",data.indBA,"#8a6abf"],["form",data.formRes,"#2a6a5a"],["contrast",data.conAlign,"#5a8ac9"],["expect",data.expOvlp,"#d4a843"]].map(([label,val,color])=><div key={label} style={{display:"flex",alignItems:"center",gap:3,padding:"2px 6px",background:"#0e1219",borderRadius:3,border:"1px solid #1a2130"}}><span style={{color,fontWeight:600}}>{label}</span><div style={{width:30,height:3,background:"#0a0e14",borderRadius:2}}><div style={{width:`${Math.min(val,1)*100}%`,height:"100%",background:color,borderRadius:2}}/></div><span style={{color:"#4a5a6a"}}>{(val*100).toFixed(0)}%</span></div>)}</div></div>;
if(data.type==="score"&&data.steps)return<div style={{marginTop:6}}>{data.steps.map((st,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:4,marginBottom:2}}><span style={{width:70,fontSize:9,fontWeight:600,color:st.surprise<.3?"#48b89a":st.surprise<.7?"#a8b4c4":"#c05050"}}>{st.word}</span><div style={{flex:1,height:3,background:"#0a0e14",borderRadius:2}}><div style={{width:`${st.surprise*100}%`,height:"100%",background:st.surprise<.3?"#2a6a5a":st.surprise<.7?"#d4a843":"#c05050",borderRadius:2}}/></div><span style={{fontSize:7,color:"#4a5a6a",width:24,textAlign:"right"}}>{(st.surprise*100).toFixed(0)}%</span>{st.afGate>0.05&&<span style={{fontSize:6,color:"#48b89a",width:20,textAlign:"right"}}>⚡</span>}</div>)}</div>;
return null;}
// ═══ App ═══
export default function App(){const[eng,setEng]=useState(null);const[msgs,setMsgs]=useState([]);const[input,setInput]=useState("");const[loading,setLoading]=useState(true);const endRef=useRef(null);
useEffect(()=>{(async()=>{let e=new E();try{const s=await IDB.get("shifu");if(s)e=E.from(s);}catch{}setEng(e);const st=e.stats();setMsgs([{role:"bot",text:st.vocab>0?`I remember ${st.vocab} words etched across ${st.sent} sentences. What would you like to explore?`:"I am Shifu. A stone, waiting for the chisel.\n60 dimensions. 7 faces. Feed me text to begin.\nType help for commands.",rich:null}]);setLoading(false);})();},[]);
useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"});},[msgs]);
const send=useCallback(()=>{if(!eng||!input.trim())return;const msg=input.trim();setInput("");setMsgs(p=>[...p,{role:"user",text:msg,rich:null}]);setTimeout(async()=>{const intent=parseIntent(msg);if(intent.type==="reset"){const fresh=new E();setEng(fresh);try{await IDB.del("shifu");}catch{}setMsgs(p=>[...p,{role:"bot",text:"Memory cleared. Fresh vessel.",rich:null}]);return;}const{text,rich}=respond(intent,eng);try{await IDB.set("shifu",eng.save());}catch{}setMsgs(p=>[...p,{role:"bot",text,rich}]);},20);},[eng,input]);
if(loading)return<div style={{display:"flex",alignItems:"center",justifyContent:"center",height:"100vh",background:"#0a0e14",color:"#48b89a",fontFamily:"'IBM Plex Mono',monospace"}}>Loading...</div>;
return(<div style={{height:"100vh",display:"flex",flexDirection:"column",background:"#0a0e14",fontFamily:"'IBM Plex Mono',monospace"}}>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=Instrument+Serif&display=swap" rel="stylesheet"/>
<header style={{padding:"12px 20px",borderBottom:"1px solid #1a2130",display:"flex",alignItems:"center",gap:12,flexShrink:0}}><div style={{fontFamily:"'Instrument Serif',Georgia,serif",fontSize:22,color:"#48b89a",letterSpacing:1}}>Shifu</div><div style={{fontSize:8,color:"#4a5a6a",flex:1}}>60D · 7ch · affinity-gated</div><div style={{fontSize:9,color:"#4a5a6a"}}>{eng?.stats().vocab||0} words</div></header>
<div style={{flex:1,overflow:"auto",padding:"16px 16px 8px"}}><div style={{maxWidth:600,margin:"0 auto"}}>{msgs.map((m,i)=><div key={i} style={{display:"flex",justifyContent:m.role==="user"?"flex-end":"flex-start",marginBottom:10}}><div style={{maxWidth:"85%",padding:"10px 14px",borderRadius:12,background:m.role==="user"?"#1a2a3a":"#0e1219",border:`1px solid ${m.role==="user"?"#2a3a4a":"#1a2130"}`,borderBottomRightRadius:m.role==="user"?4:12,borderBottomLeftRadius:m.role==="user"?12:4}}><div style={{fontSize:11,color:m.role==="user"?"#8ab4d4":"#a8b4c4",lineHeight:1.7,whiteSpace:"pre-wrap"}}>{m.text}</div><RichViz data={m.rich}/></div></div>)}<div ref={endRef}/></div></div>
<div style={{padding:"12px 16px",borderTop:"1px solid #1a2130",flexShrink:0}}><div style={{maxWidth:600,margin:"0 auto",display:"flex",gap:8}}><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Feed text, explore, compare, affinity, correct, score..." style={{flex:1,padding:"10px 14px",background:"#0e1219",border:"1px solid #1a2130",borderRadius:8,color:"#a8b4c4",fontFamily:"'IBM Plex Mono',monospace",fontSize:12,outline:"none"}}/><button onClick={send} style={{padding:"10px 20px",background:"#0d211c",border:"1px solid #1a4a3c",borderRadius:8,color:"#48b89a",fontFamily:"'IBM Plex Mono',monospace",fontSize:12,fontWeight:600,cursor:"pointer"}}>Send</button></div></div>
</div>);}
