// SHIFU v2.0 — The Embryo
// One cell. No dimensions. No channels. Structure emerges from exposure.
// Pressure replaces curiosity: the graph knows its own shape.
const VERSION="2.0.0";
const OCR={"0,o":.1,"1,l":.2,"1,i":.2,"5,s":.3,"8,b":.3,"6,g":.4,"l,i":.2,"m,n":.4,"u,v":.5,"c,e":.5,"r,n":.3,"d,o":.3,"f,t":.4,"h,b":.4,"a,e":.4,"a,o":.4,"u,n":.4,"e,i":.4,"f,l":.4,"s,e":.5,"b,d":.4};
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
function editDistance(a,b){a=a.toLowerCase();b=b.toLowerCase();if(a.length<b.length)return editDistance(b,a);if(!b.length)return a.length;let p=Array.from({length:b.length+1},(_,i)=>i);for(let i=0;i<a.length;i++){const c=[i+1];for(let j=0;j<b.length;j++)c.push(Math.min(p[j+1]+1,c[j]+1,p[j]+(a[i]===b[j]?0:1)));p=c;}return p[b.length];}
function ocrDistance(a,b){a=a.toLowerCase();b=b.toLowerCase();if(a.length<b.length)return ocrDistance(b,a);if(!b.length)return a.length;let p=Array.from({length:b.length+1},(_,i)=>i);for(let i=0;i<a.length;i++){const c=[i+1];for(let j=0;j<b.length;j++){const k=[a[i],b[j]].sort().join(",");c.push(Math.min(p[j+1]+1,c[j]+1,p[j]+(a[i]===b[j]?0:(OCR[k]??1))));}p=c;}return p[b.length];}
function sharedBigrams(a,b){a=a.toLowerCase();b=b.toLowerCase();if(a.length<2||b.length<2)return 0;const bg=s=>{const m=new Map();for(let i=0;i<s.length-1;i++){const k=s.slice(i,i+2);m.set(k,(m.get(k)||0)+1);}return m;};const ba=bg(a),bb=bg(b);let inter=0;for(const[k,v]of ba)inter+=Math.min(v,bb.get(k)||0);const tot=[...ba.values()].reduce((a,b)=>a+b,0)+[...bb.values()].reduce((a,b)=>a+b,0);return tot?2*inter/tot:0;}
function tokenize(raw){return(raw.toLowerCase().match(/[a-z0-9]+/g)||[]).filter(w=>w.length>1);}

class ShifuEmbryo{
constructor(){this.nodes={};this.sentenceCount=0;this.tokenCount=0;}
_nn(w){return{chars:w,freq:0,firstSeen:null,lastSeen:null,positions:[],gaps:[],sentLengths:[],neighbors:{},next:{},prev:{},next2:{}};}
feed(raw){const ws=tokenize(raw);if(ws.length<2)return 0;this.sentenceCount++;const len=ws.length;for(let i=0;i<ws.length;i++){const w=ws[i];const nd=this.nodes[w]??=this._nn(w);const rp=i/Math.max(ws.length-1,1);this.tokenCount++;nd.freq++;nd.firstSeen??=this.sentenceCount;if(nd.lastSeen!==null)nd.gaps.push(this.sentenceCount-nd.lastSeen);nd.lastSeen=this.sentenceCount;nd.positions.push(rp);nd.sentLengths.push(len);for(let j=Math.max(0,i-3);j<Math.min(ws.length,i+4);j++){if(j!==i)nd.neighbors[ws[j]]=(nd.neighbors[ws[j]]||0)+1;}if(i<ws.length-1)nd.next[ws[i+1]]=(nd.next[ws[i+1]]||0)+1;if(i>0)nd.prev[ws[i-1]]=(nd.prev[ws[i-1]]||0)+1;if(i<ws.length-2){const b=ws[i+1],c=ws[i+2];nd.next2[b]??={};nd.next2[b][c]=(nd.next2[b][c]||0)+1;}if(nd.positions.length>200)nd.positions=nd.positions.slice(-200);if(nd.gaps.length>100)nd.gaps=nd.gaps.slice(-100);if(nd.sentLengths.length>100)nd.sentLengths=nd.sentLengths.slice(-100);}return ws.length;}
feedText(t){const s=t.split(/[.!?\n]+/).map(s=>s.trim()).filter(s=>s.length>5);let tk=0;for(const x of s)tk+=this.feed(x);return{sentences:s.length,tokens:tk};}
depth(w){const n=this.nodes[w];if(!n)return{level:"unborn",evidence:0};if(n.freq===1)return{level:"surface",evidence:.1};if(n.freq<5)return{level:"shallow",evidence:.2};const nb=Object.keys(n.neighbors).length,sq=Object.keys(n.next).length+Object.keys(n.prev).length;const ev=Math.min((n.freq/50)*.3+(nb/20)*.3+(sq/10)*.2+(n.positions.length/50)*.2,1);if(ev<.3)return{level:"forming",evidence:ev};if(ev<.7)return{level:"structured",evidence:ev};return{level:"deep",evidence:ev};}
compare(a,b){const al=a.toLowerCase(),bl=b.toLowerCase(),na=this.nodes[al],nb=this.nodes[bl],sig={},wt={};sig.editSim=1-editDistance(al,bl)/Math.max(al.length,bl.length,1);sig.bigramSim=sharedBigrams(al,bl);sig.ocrSim=1-ocrDistance(al,bl)/Math.max(al.length,bl.length,1);wt.char=.05;if(!na||!nb)return{similarity:sig.editSim*.3+sig.bigramSim*.3+sig.ocrSim*.4,signals:sig,weights:wt,totalWeight:.05,depth:"surface"};const nbA=Object.keys(na.neighbors),nbBs=new Set(Object.keys(nb.neighbors)),shared=nbA.filter(x=>nbBs.has(x)),union=new Set([...nbA,...nbBs]);if(union.size>0){const rw=w=>1/Math.max(Math.log2((this.nodes[w]?.freq||0)+1),1);const sw=shared.reduce((s,w)=>s+rw(w),0),uw=[...union].reduce((s,w)=>s+rw(w),0);sig.neighborOverlap=uw>0?sw/uw:0;wt.neighbor=Math.min(union.size/10,.35);}const totA=Object.values(na.next).reduce((s,v)=>s+v,0),totB=Object.values(nb.next).reduce((s,v)=>s+v,0);if(totA>0||totB>0){sig.expectsAB=totA?(na.next[bl]||0)/totA:0;sig.expectsBA=totB?(nb.next[al]||0)/totB:0;sig.directional=Math.abs(sig.expectsAB-sig.expectsBA);wt.seq=Math.min((totA+totB)/20,.25);}const nx2AB=na.next2?.[bl]?Object.keys(na.next2[bl]).length:0,nx2BA=nb.next2?.[al]?Object.keys(nb.next2[al]).length:0;if(nx2AB>0||nx2BA>0){sig.trajectoryAB=Math.min(nx2AB/5,1);sig.trajectoryBA=Math.min(nx2BA/5,1);wt.traj=.15;}if(na.positions.length>=3&&nb.positions.length>=3){sig.posSim=1-Math.min(Math.abs(mean(na.positions)-mean(nb.positions))*2,1);wt.pos=Math.min(Math.min(na.positions.length,nb.positions.length)/20,.10);}let indAB=0;for(const mid of Object.keys(na.next))if(this.nodes[mid]?.next[bl])indAB++;if(indAB>0){sig.indirectAB=Math.min(indAB/5,1);wt.indirect=Math.min(indAB/10,.15);}let sim=0,tw=0;if(wt.char){sim+=(sig.editSim*.3+sig.bigramSim*.3+sig.ocrSim*.4)*wt.char;tw+=wt.char;}if(wt.neighbor){sim+=sig.neighborOverlap*wt.neighbor;tw+=wt.neighbor;}if(wt.seq){sim+=Math.max(sig.expectsAB||0,sig.expectsBA||0)*wt.seq;tw+=wt.seq;}if(wt.traj){sim+=Math.max(sig.trajectoryAB||0,sig.trajectoryBA||0)*wt.traj;tw+=wt.traj;}if(wt.pos){sim+=sig.posSim*wt.pos;tw+=wt.pos;}if(wt.indirect){sim+=sig.indirectAB*wt.indirect;tw+=wt.indirect;}if(tw>0)sim/=tw;const d=tw>.5?"deep":tw>.3?"structured":tw>.15?"forming":"shallow";return{similarity:sim,signals:sig,weights:wt,totalWeight:tw,depth:d};}
affinity(a,b){const al=a.toLowerCase(),bl=b.toLowerCase(),na=this.nodes[al],nb=this.nodes[bl];if(!na||!nb)return{a:al,b:bl,mutual:0,known:false};const nbA=Object.keys(na.neighbors),nbBs=new Set(Object.keys(nb.neighbors)),shared=nbA.filter(x=>nbBs.has(x)),rw=w=>1/Math.max(Math.log2((this.nodes[w]?.freq||0)+1),1),sw=shared.reduce((s,w)=>s+rw(w),0),uw=[...new Set([...nbA,...nbBs])].reduce((s,w)=>s+rw(w),0),orbit=uw>0?sw/uw:0;const totA=Object.values(na.next||{}).reduce((s,v)=>s+v,0),totB=Object.values(nb.next||{}).reduce((s,v)=>s+v,0),pullAB=totA?(na.next[bl]||0)/totA:0,pullBA=totB?(nb.next[al]||0)/totB:0;let indAB=0,indBA=0;for(const mid of Object.keys(na.next||{}))if(this.nodes[mid]?.next[bl])indAB++;for(const mid of Object.keys(nb.next||{}))if(this.nodes[mid]?.next[al])indBA++;indAB=Math.min(indAB/5,1);indBA=Math.min(indBA/5,1);const charSim=1-editDistance(al,bl)/Math.max(al.length,bl.length,1);const fwA=new Set(Object.keys(na.next||{})),fwB=new Set(Object.keys(nb.next||{})),fwU=new Set([...fwA,...fwB]),expOvlp=fwU.size?[...fwA].filter(x=>fwB.has(x)).length/fwU.size:0;let posAlign=0;if(na.positions.length>=3&&nb.positions.length>=3)posAlign=1-Math.min(Math.abs(mean(na.positions)-mean(nb.positions))*3,1);const afAB=charSim*.05+orbit*.35+pullAB*.20+indAB*.20+expOvlp*.15+posAlign*.05,afBA=charSim*.05+orbit*.35+pullBA*.20+indBA*.20+expOvlp*.15+posAlign*.05;return{a:al,b:bl,orbit,pullAB,pullBA,indAB,indBA,charSim,expOvlp,posAlign,afAB,afBA,mutual:(afAB+afBA)/2,asym:Math.abs(afAB-afBA),known:true};}
scoreSentence(raw){const ws=tokenize(raw);if(ws.length<2)return{words:ws,steps:[],meanSurprise:0,coherence:0};const steps=[];let total=0;const field=new Map();for(let i=0;i<ws.length;i++){const w=ws[i],node=this.nodes[w],step={word:w,pos:i,known:!!node};let sig=0,wts=0;if(i>0){const prev=this.nodes[ws[i-1]];if(prev?.next){const tot=Object.values(prev.next).reduce((a,b)=>a+b,0);step.seqS=1-((prev.next[w]||0)/Math.max(tot,1));sig+=step.seqS*.35;wts+=.35;}}if(i>=2){const pp=this.nodes[ws[i-2]],nx2=pp?.next2?.[ws[i-1]];if(nx2){const tot=Object.values(nx2).reduce((a,b)=>a+b,0);step.trajS=1-((nx2[w]||0)/Math.max(tot,1));sig+=step.trajS*.30;wts+=.30;}}if(i>0&&field.size>0){const fw=field.get(w)||0,mx=Math.max(...field.values(),1);step.fieldS=1-fw/mx;sig+=step.fieldS*.35;wts+=.35;}step.afGate=0;if(i>0&&node){const pn=this.nodes[ws[i-1]];if(pn?.neighbors&&node.neighbors){const pN=Object.keys(pn.neighbors),wN=new Set(Object.keys(node.neighbors)),sh=pN.filter(x=>wN.has(x)).length,un=new Set([...pN,...wN]).size;step.afGate=un?sh/un:0;}}step.surprise=wts>0?(sig/wts)*(1-step.afGate*.3):(node?.5:1);total+=step.surprise;step.cumS=total;steps.push(step);if(node?.neighbors)for(const[nb,cnt]of Object.entries(node.neighbors))field.set(nb,(field.get(nb)||0)+cnt);field.set(w,(field.get(w)||0)+10);}const ms=steps.length?total/steps.length:0;return{words:ws,steps,meanSurprise:ms,coherence:1-Math.min(ms,1)};}
pressure(){const map=[];for(const[word,node]of Object.entries(this.nodes)){let inbound=0;for(const[,other]of Object.entries(this.nodes))if(other.next[word])inbound+=other.next[word];const actual=Object.keys(node.neighbors).length+Object.keys(node.next).length+Object.keys(node.prev).length;const p=actual-inbound;const nbrs=Object.keys(node.neighbors);let internal=0,pairs=0;for(let i=0;i<Math.min(nbrs.length,15);i++)for(let j=i+1;j<Math.min(nbrs.length,15);j++){pairs++;if(this.nodes[nbrs[i]]?.neighbors[nbrs[j]])internal++;}const closure=pairs>0?internal/pairs:1;map.push({word,pressure:p,inbound,actual,closure,freq:node.freq,depth:this.depth(word).level});}return map.sort((a,b)=>a.pressure-b.pressure);}
vacuums(k=10){return this.pressure().filter(p=>p.pressure<0).slice(0,k);}
surpluses(k=10){return this.pressure().filter(p=>p.pressure>0).sort((a,b)=>b.pressure-a.pressure).slice(0,k);}
bridges(k=10){return this.pressure().filter(p=>p.closure<.3&&p.freq>=3).slice(0,k);}
correct(garbled,k=5){const g=garbled.toLowerCase(),cands=new Set();for(const w of Object.keys(this.nodes))if(Math.abs(w.length-g.length)<=3)cands.add(w);for(let i=0;i<g.length-1;i++){const bg=g.slice(i,i+2);for(const w of Object.keys(this.nodes))if(w.includes(bg))cands.add(w);}const scored=[...cands].map(w=>{const o=1-ocrDistance(g,w)/Math.max(g.length,w.length,1),b=sharedBigrams(g,w);return{word:w,score:o*.7+b*.3};});scored.sort((a,b)=>b.score-a.score||(this.nodes[b.word]?.freq||0)-(this.nodes[a.word]?.freq||0));const top=scored.slice(0,k),conf=top.length>=2?top[0].score-top[1].score:top.length?1:0;return{candidates:top,confidence:conf};}
similar(w,k=8){const wl=w.toLowerCase(),out=[];for(const c of Object.keys(this.nodes)){if(c===wl)continue;out.push({word:c,...this.compare(wl,c)});}return out.sort((a,b)=>b.similarity-a.similarity).slice(0,k);}
stats(){const v=Object.keys(this.nodes).length,depths={unborn:0,surface:0,shallow:0,forming:0,structured:0,deep:0};for(const w of Object.keys(this.nodes))depths[this.depth(w).level]++;return{version:VERSION,vocab:v,sentences:this.sentenceCount,tokens:this.tokenCount,depths};}
serialize(){return JSON.stringify({version:VERSION,nodes:Object.fromEntries(Object.entries(this.nodes).map(([w,n])=>[w,{chars:n.chars,freq:n.freq,firstSeen:n.firstSeen,lastSeen:n.lastSeen,positions:n.positions.slice(-200),gaps:n.gaps.slice(-100),sentLengths:n.sentLengths.slice(-100),neighbors:n.neighbors,next:n.next,prev:n.prev,next2:n.next2}])),sentenceCount:this.sentenceCount,tokenCount:this.tokenCount});}
static deserialize(json){const d=JSON.parse(json),e=new ShifuEmbryo();e.sentenceCount=d.sentenceCount||0;e.tokenCount=d.tokenCount||0;for(const[w,n]of Object.entries(d.nodes||{})){e.nodes[w]={chars:n.chars||w,freq:n.freq||0,firstSeen:n.firstSeen,lastSeen:n.lastSeen,positions:n.positions||[],gaps:n.gaps||[],sentLengths:n.sentLengths||[],neighbors:n.neighbors||{},next:n.next||{},prev:n.prev||{},next2:n.next2||{}};}return e;}}
module.exports={ShifuEmbryo,VERSION,editDistance,ocrDistance,sharedBigrams,tokenize};
