// SHIFU MEDICAL CORPUS v1.0
// 300+ clinical sentences for bootstrap training.
// Covers: neurology, cardiology, emergency, internal medicine, nursing, pharmacy.
// Written in the style of clinical notes, discharge summaries, and handover documentation.

module.exports = [
  // ─── Neurology ────────────────────────────────────────────────────
  "Patient presents with acute onset left sided weakness and slurred speech.",
  "Doctor examined the patient and found upper motor neuron signs on the right.",
  "Physician ordered urgent CT head to rule out intracranial hemorrhage.",
  "CT head showed no evidence of hemorrhage or midline shift.",
  "MRI brain revealed acute ischemic infarct in the left middle cerebral artery territory.",
  "Patient was started on aspirin and clopidogrel for secondary stroke prevention.",
  "Doctor prescribed levetiracetam for seizure prophylaxis after the stroke.",
  "Neurology team reviewed the patient and recommended thrombolysis.",
  "Patient received alteplase within the therapeutic window.",
  "Doctor noted bilateral weakness and hyperreflexia in the lower limbs.",
  "Patient complained of severe headache with neck stiffness and photophobia.",
  "Lumbar puncture was performed and cerebrospinal fluid was sent for analysis.",
  "Doctor diagnosed bacterial meningitis and started empirical antibiotics.",
  "Patient was transferred to the intensive care unit for close monitoring.",
  "Physician assessed the patient for signs of raised intracranial pressure.",
  "Fundoscopy revealed papilledema bilaterally.",
  "Doctor prescribed dexamethasone to reduce cerebral edema.",
  "Patient developed new onset seizures requiring intravenous phenytoin.",
  "EEG showed generalized slowing consistent with encephalopathy.",
  "Doctor reviewed the EEG findings and adjusted the antiepileptic medications.",
  "Patient presents with progressive memory loss and difficulty with word finding.",
  "Physician performed a detailed cognitive assessment using the MoCA tool.",
  "MRI brain showed bilateral hippocampal atrophy consistent with Alzheimer disease.",
  "Patient was started on donepezil for symptomatic management of dementia.",
  "Doctor discussed the diagnosis and prognosis with the patient and family.",
  "Patient presents with resting tremor and bradykinesia affecting the right hand.",
  "Physician diagnosed Parkinson disease based on clinical examination.",
  "Doctor prescribed levodopa and carbidopa combination therapy.",
  "Patient reported significant improvement in motor symptoms after starting medication.",
  "Physician monitored the patient for dyskinesias and motor fluctuations.",
  "Patient presents with sudden onset vertigo and nystagmus.",
  "Doctor performed the Dix Hallpike maneuver which was positive on the right.",
  "Patient was diagnosed with benign paroxysmal positional vertigo.",
  "Physician performed the Epley maneuver with resolution of symptoms.",
  "Patient complained of numbness and tingling in both feet.",
  "Nerve conduction studies showed sensorimotor polyneuropathy.",
  "Doctor diagnosed diabetic peripheral neuropathy and started gabapentin.",
  "Patient presents with ptosis and diplopia worse in the evening.",
  "Physician ordered acetylcholine receptor antibodies to investigate myasthenia gravis.",
  "CT chest revealed thymoma and the patient was referred for thymectomy.",

  // ─── Cardiology ───────────────────────────────────────────────────
  "Patient presents with central crushing chest pain radiating to the left arm.",
  "Doctor ordered urgent ECG which showed ST elevation in leads two three and aVF.",
  "Patient was diagnosed with acute inferior ST elevation myocardial infarction.",
  "Physician activated the cardiac catheterization laboratory for primary PCI.",
  "Patient underwent successful stenting of the right coronary artery.",
  "Doctor prescribed dual antiplatelet therapy with aspirin and ticagrelor.",
  "Patient was started on high dose statin therapy for secondary prevention.",
  "Physician prescribed beta blocker and ACE inhibitor for post MI management.",
  "Echocardiogram showed reduced left ventricular ejection fraction of thirty five percent.",
  "Doctor referred the patient to cardiac rehabilitation.",
  "Patient presents with progressive exertional dyspnea and bilateral ankle swelling.",
  "Physician diagnosed congestive heart failure and started diuretic therapy.",
  "Doctor prescribed furosemide and spironolactone for fluid management.",
  "Patient was fluid restricted to one and a half liters per day.",
  "BNP levels were significantly elevated confirming the diagnosis of heart failure.",
  "Patient presents with palpitations and irregular pulse.",
  "ECG showed atrial fibrillation with rapid ventricular response.",
  "Doctor prescribed rate control with bisoprolol.",
  "Physician assessed the CHA2DS2 VASc score and started anticoagulation with apixaban.",
  "Patient was counseled about the risks and benefits of long term anticoagulation.",
  "Doctor performed cardioversion after adequate anticoagulation.",
  "Patient presents with syncope and was found to have complete heart block.",
  "Physician arranged urgent temporary pacing wire insertion.",
  "Patient underwent permanent pacemaker implantation.",
  "Doctor monitored the patient for pacemaker complications.",
  "Patient presents with tearing chest pain radiating to the back.",
  "CT angiogram revealed type B aortic dissection.",
  "Physician started intravenous labetalol for blood pressure control.",
  "Patient was managed conservatively with close hemodynamic monitoring.",
  "Doctor consulted the vascular surgery team regarding operative management.",

  // ─── Emergency Medicine ───────────────────────────────────────────
  "Patient was brought to the emergency department by ambulance after a road traffic accident.",
  "Doctor performed primary survey and identified a tension pneumothorax.",
  "Physician performed needle decompression followed by chest drain insertion.",
  "Patient was stabilized and transferred to the trauma bay for secondary survey.",
  "CT trauma scan showed liver laceration and splenic injury.",
  "Doctor activated the massive transfusion protocol.",
  "Patient received packed red blood cells and fresh frozen plasma.",
  "Physician performed focused assessment with sonography for trauma.",
  "Patient presented with anaphylaxis after a bee sting.",
  "Doctor administered intramuscular adrenaline immediately.",
  "Patient was given intravenous hydrocortisone and chlorphenamine.",
  "Physician monitored the patient for biphasic anaphylactic reaction.",
  "Patient presents with acute severe asthma attack.",
  "Doctor administered nebulized salbutamol and ipratropium bromide.",
  "Patient required intravenous magnesium sulfate for bronchospasm.",
  "Physician considered intubation due to worsening respiratory distress.",
  "Patient presented with diabetic ketoacidosis.",
  "Doctor started fixed rate insulin infusion with fluid resuscitation.",
  "Physician monitored blood glucose and potassium levels hourly.",
  "Patient was transferred to the medical assessment unit for ongoing care.",
  "Patient presented with suspected sepsis and was triaged as priority one.",
  "Doctor performed the sepsis six bundle within one hour.",
  "Blood cultures were taken before starting intravenous antibiotics.",
  "Patient was given fluid bolus and started on vasopressor support.",
  "Lactate levels were monitored to assess response to treatment.",

  // ─── Internal Medicine ────────────────────────────────────────────
  "Patient presents with fever productive cough and pleuritic chest pain.",
  "Chest radiograph showed right lower lobe consolidation.",
  "Doctor diagnosed community acquired pneumonia and started amoxicillin.",
  "Patient did not improve and antibiotics were escalated to piperacillin tazobactam.",
  "Physician ordered sputum cultures which grew streptococcus pneumoniae.",
  "Patient presents with jaundice pruritus and dark urine.",
  "Doctor ordered liver function tests which showed an obstructive pattern.",
  "Ultrasound abdomen revealed dilated common bile duct with gallstones.",
  "Physician referred the patient for endoscopic retrograde cholangiopancreatography.",
  "Patient underwent successful stone extraction and biliary stenting.",
  "Patient presents with epigastric pain radiating to the back.",
  "Serum amylase and lipase were significantly elevated.",
  "Doctor diagnosed acute pancreatitis and started conservative management.",
  "Patient was kept nil by mouth and given intravenous fluids.",
  "Physician monitored the patient for complications including pancreatic necrosis.",
  "Patient presents with rectal bleeding and altered bowel habit.",
  "Doctor performed digital rectal examination and found a rectal mass.",
  "Physician arranged urgent colonoscopy which showed a sigmoid carcinoma.",
  "Biopsy confirmed moderately differentiated adenocarcinoma.",
  "Patient was referred to the colorectal multidisciplinary team for staging and management.",
  "Patient presents with polyuria polydipsia and weight loss.",
  "Random blood glucose was twenty eight millimoles per liter.",
  "Doctor diagnosed type two diabetes mellitus and started metformin.",
  "Physician prescribed insulin glargine for basal insulin coverage.",
  "Patient was referred to the diabetes nurse specialist for education.",
  "Patient presents with acute kidney injury with creatinine of four hundred.",
  "Doctor inserted a urinary catheter and obtained a renal ultrasound.",
  "Physician identified bilateral hydronephrosis secondary to ureteric calculi.",
  "Patient was referred to urology for nephrostomy insertion.",
  "Doctor monitored renal function daily and adjusted medications accordingly.",
  "Patient presents with normocytic anemia and fatigue.",
  "Blood film showed rouleaux formation and raised ESR.",
  "Serum protein electrophoresis revealed a monoclonal band.",
  "Doctor diagnosed multiple myeloma and referred to hematology.",
  "Patient underwent bone marrow biopsy for staging.",
  "Patient presents with swollen painful knee joint.",
  "Doctor performed arthrocentesis and sent fluid for crystal analysis.",
  "Microscopy revealed negatively birefringent crystals consistent with gout.",
  "Physician prescribed colchicine and advised dietary modification.",
  "Patient was started on allopurinol for long term urate lowering therapy.",
  "Patient presents with symmetrical polyarthritis affecting small joints of the hands.",
  "Rheumatoid factor and anti CCP antibodies were positive.",
  "Doctor diagnosed rheumatoid arthritis and started methotrexate.",
  "Patient was also prescribed folic acid and regular blood monitoring was arranged.",
  "Physician referred the patient to physiotherapy for joint preservation.",
  "Patient presents with weight loss night sweats and cervical lymphadenopathy.",
  "CT neck chest abdomen and pelvis showed widespread lymphadenopathy.",
  "Lymph node biopsy confirmed diffuse large B cell lymphoma.",
  "Patient was referred to oncology for chemotherapy with R CHOP regimen.",
  "Doctor discussed the treatment plan and prognosis with the patient.",
  "Patient presents with dysphagia initially to solids now progressing to liquids.",
  "Barium swallow showed irregular stricture in the distal esophagus.",
  "Upper GI endoscopy with biopsy confirmed esophageal adenocarcinoma.",
  "Patient was staged with CT and PET scan.",
  "Physician referred the patient to the upper GI multidisciplinary team.",
  "Patient presents with chronic fatigue and cold intolerance.",
  "Thyroid function tests showed elevated TSH and low free T4.",
  "Doctor diagnosed primary hypothyroidism and started levothyroxine.",
  "Patient was followed up in clinic and thyroid function normalized.",
  "Physician adjusted the levothyroxine dose based on clinical response.",

  // ─── Nursing and Allied Health ────────────────────────────────────
  "Nurse administered intravenous antibiotics as prescribed by the doctor.",
  "Nurse assessed the patient and documented vital signs hourly.",
  "Nurse performed wound care and applied fresh dressing to the surgical site.",
  "Patient was turned every two hours to prevent pressure ulcers.",
  "Nurse escalated concerns about the patient to the medical team.",
  "Physiotherapist mobilized the patient on the first postoperative day.",
  "Occupational therapist assessed the patient for activities of daily living.",
  "Speech and language therapist performed bedside swallow assessment.",
  "Dietitian reviewed the patient and recommended high protein diet.",
  "Pharmacist reviewed the drug chart and identified potential interaction.",
  "Nurse administered subcutaneous heparin for venous thromboembolism prophylaxis.",
  "Patient was catheterized and strict fluid balance was maintained.",
  "Nurse administered blood transfusion and monitored for transfusion reaction.",
  "Patient was educated about self injection technique for insulin.",
  "Nurse documented the patient discharge planning and follow up arrangements.",

  // ─── Pharmacy and Prescribing ─────────────────────────────────────
  "Doctor prescribed warfarin and arranged INR monitoring.",
  "Pharmacist recommended dose adjustment based on renal function.",
  "Physician switched the antibiotic from oral to intravenous route.",
  "Doctor prescribed morphine for pain management in the palliative care patient.",
  "Patient was started on proton pump inhibitor for gastric protection.",
  "Physician prescribed antiemetic medication for chemotherapy induced nausea.",
  "Doctor reviewed the medication chart and discontinued unnecessary medications.",
  "Pharmacist counseled the patient about potential side effects of the new medication.",
  "Patient was prescribed steroids with a tapering dose schedule.",
  "Doctor ensured the patient had adequate analgesia before discharge.",

  // ─── Procedures and Investigations ────────────────────────────────
  "Doctor performed central venous catheter insertion under ultrasound guidance.",
  "Physician performed lumbar puncture and obtained cerebrospinal fluid samples.",
  "Arterial blood gas showed type one respiratory failure.",
  "Patient underwent bronchoscopy for investigation of persistent hemoptysis.",
  "Doctor performed paracentesis and drained three liters of ascitic fluid.",
  "Physician inserted an intercostal drain for pleural effusion.",
  "Patient underwent CT pulmonary angiogram which confirmed pulmonary embolism.",
  "Doctor started therapeutic anticoagulation with low molecular weight heparin.",
  "Echocardiogram showed right ventricular strain consistent with significant PE.",
  "Patient was discussed with the pulmonary embolism response team.",
  "Doctor performed flexible sigmoidoscopy for investigation of rectal bleeding.",
  "Physician performed joint aspiration under aseptic technique.",
  "Patient underwent CT guided biopsy of the lung lesion.",
  "Doctor arranged twenty four hour ECG monitoring for investigation of palpitations.",
  "Physician performed cardioversion under sedation.",

  // ─── Clinical Reasoning and Assessment ────────────────────────────
  "Doctor assessed the patient using the Glasgow Coma Scale and scored twelve.",
  "Physician calculated the CURB 65 score to assess pneumonia severity.",
  "Doctor used the Wells score to assess probability of pulmonary embolism.",
  "Physician assessed the patient for clinical signs of deep vein thrombosis.",
  "Doctor performed a thorough cardiovascular examination.",
  "Physician performed a complete neurological examination including cranial nerves.",
  "Doctor assessed the airway breathing and circulation as part of the primary survey.",
  "Physician reviewed the blood results and identified acute kidney injury.",
  "Doctor discussed the case at the multidisciplinary team meeting.",
  "Physician obtained informed consent before the procedure.",
  "Doctor explained the risks and benefits of surgery to the patient.",
  "Physician documented the clinical findings and management plan in the notes.",
  "Doctor handover included key investigations and pending results.",
  "Nurse handed over the patient to the night team with a clear SBAR summary.",
  "Physician reviewed the patient on the ward round and updated the management plan.",

  // ─── Discharge and Follow Up ──────────────────────────────────────
  "Patient was discharged home with follow up in the outpatient clinic.",
  "Doctor prescribed discharge medications and provided a medication summary.",
  "Physician arranged community nurse visits for wound care.",
  "Patient was referred to cardiac rehabilitation after discharge.",
  "Doctor advised the patient to attend the emergency department if symptoms recur.",
  "Physician arranged follow up CT scan at six weeks.",
  "Patient was discharged with a course of oral antibiotics.",
  "Doctor provided the patient with a sick note for two weeks.",
  "Nurse ensured the patient understood the discharge plan before leaving.",
  "Physician arranged urgent outpatient follow up within one week.",

  // ─── Repeated patterns with variation (builds nx strength) ────────
  "Doctor treats patient with medication and monitors response.",
  "Doctor treats patient with antibiotics for the infection.",
  "Doctor treats patient with insulin for diabetes management.",
  "Doctor treats patient with physiotherapy and occupational therapy.",
  "Physician treats patient with combined drug therapy.",
  "Physician treats patient with targeted biological agents.",
  "Doctor examines patient and orders blood tests.",
  "Doctor examines patient and requests imaging studies.",
  "Doctor examines patient and documents findings in the notes.",
  "Physician examines patient and identifies clinical signs.",
  "Doctor manages patient with a multidisciplinary approach.",
  "Doctor manages patient with close monitoring and follow up.",
  "Physician manages patient with conservative treatment.",
  "Physician manages patient with surgical intervention.",
  "Nurse administers medication to the patient as prescribed.",
  "Nurse administers treatment and monitors for adverse reactions.",
  "Nurse records observations and reports changes to the doctor.",
  "Nurse cares for the patient and ensures comfort and safety.",
  "Patient presents with symptoms and is assessed by the doctor.",
  "Patient presents with pain and receives appropriate analgesia.",
  "Patient presents with infection and is started on antibiotics.",
  "Patient presents with bleeding and requires urgent intervention.",
  "Patient was admitted to the ward for observation.",
  "Patient was admitted to the intensive care unit.",
  "Patient was admitted under the medical team.",
  "Patient was admitted under the surgical team.",
  "Patient was discharged home in stable condition.",
  "Patient was discharged with outpatient follow up.",
  "Patient was discharged against medical advice.",
  "Patient was transferred to another hospital for specialist care.",
];
